spring:
  application:
    name: spring-boot-production-template
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      fail-on-unknown-properties: false

server:
  port: 8080
  forward-headers-strategy: NONE
  servlet:
    context-path: /spring-boot-production-template

rest:
  logging:
    enabled: true
  masking:
    enabled: true
  max:
    loggable:
      size: 409600

feign:
  logging:
    enabled: true
  masking:
    enabled: true
  short:
    logs: true
  max:
    loggable:
      size: 409600

db.logging.enabled: true